name: "jsonlog"
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    defaults:
      run:
        working-directory: "jsonlog"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade wheel pip poetry
          poetry install
      - name: "Run pytest"
        run: "poetry run pytest"
      - name: "Run mypy"
        run: "poetry run mypy ."
      - name: "Run flake8"
        run: "poetry run flake8"
