name: "Test jsonlog"
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
    defaults:
      run:
        working-directory: "jsonlog"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip pipenv
          pipenv install
      - name: "Run pytest"
        run: "pytest"
      - name: "Run mypy"
        run: "mypy ."
